/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package apk_penyewaan_alat_outdoor;

/**
 *
 * @author ASUS
 */
public class halaman_login extends javax.swing.JFrame {

    /**
     * Creates new form halaman_login
     */
    public halaman_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_biru = new javax.swing.JPanel();
        username_halaman_login = new javax.swing.JTextField();
        password_halaman_login = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        background_halaman_login = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_biru.setBackground(new java.awt.Color(0, 255, 255));
        panel_biru.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username_halaman_login.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        username_halaman_login.setText("username");
        username_halaman_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_halaman_loginActionPerformed(evt);
            }
        });
        panel_biru.add(username_halaman_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 350, 350, 60));

        password_halaman_login.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        password_halaman_login.setText("password");
        panel_biru.add(password_halaman_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 460, 350, 60));

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("MASUK");
        panel_biru.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 570, 230, 60));

        background_halaman_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1.png"))); // NOI18N
        panel_biru.add(background_halaman_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        panel_biru.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 360, 320, 50));

        getContentPane().add(panel_biru, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_halaman_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_halaman_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_halaman_loginActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halaman_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halaman_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halaman_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halaman_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halaman_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_halaman_login;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel panel_biru;
    private javax.swing.JTextField password_halaman_login;
    private javax.swing.JTextField username_halaman_login;
    // End of variables declaration//GEN-END:variables
}
