/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package apk_penyewaan_alat_outdoor;

/**
 *
 * @author ASUS
 */
public class halaman_pendaftaran_acount extends javax.swing.JFrame {

    /**
     * Creates new form halaman_pendaftaran_acount
     */
    public halaman_pendaftaran_acount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_isi_halaman_pendaftaran_acount = new javax.swing.JPanel();
        beckground_halaman_pendaftaran_acount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_isi_halaman_pendaftaran_acount.setBackground(new java.awt.Color(68, 104, 39));

        javax.swing.GroupLayout panel_isi_halaman_pendaftaran_acountLayout = new javax.swing.GroupLayout(panel_isi_halaman_pendaftaran_acount);
        panel_isi_halaman_pendaftaran_acount.setLayout(panel_isi_halaman_pendaftaran_acountLayout);
        panel_isi_halaman_pendaftaran_acountLayout.setHorizontalGroup(
            panel_isi_halaman_pendaftaran_acountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        panel_isi_halaman_pendaftaran_acountLayout.setVerticalGroup(
            panel_isi_halaman_pendaftaran_acountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        getContentPane().add(panel_isi_halaman_pendaftaran_acount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1240, 670));

        beckground_halaman_pendaftaran_acount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/2.png"))); // NOI18N
        getContentPane().add(beckground_halaman_pendaftaran_acount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halaman_pendaftaran_acount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halaman_pendaftaran_acount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halaman_pendaftaran_acount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halaman_pendaftaran_acount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halaman_pendaftaran_acount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beckground_halaman_pendaftaran_acount;
    private javax.swing.JPanel panel_isi_halaman_pendaftaran_acount;
    // End of variables declaration//GEN-END:variables
}
